name: 'Deploy Prompt Creator Agent to Cloud Run'

on:
  push:
    branches:
      - '"main"'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{secrets.GCP_IDENTITY_PROVIDER}}'
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ secrets.GCP_SEARCHER_CLOUD_RUN_SERVICE }}'
          region: '${{ secrets.GCP_REGION }}'
          # NOTE: If using a different source folder, update the image name below:
          source: '${{secrets.AGENT_DOCKERFILE_PATH}}'

      # If required, use the Cloud Run URL output in later steps
      - name: 'Show output'
        run: |-
          echo ${{ steps.deploy.outputs.url }}
