name: 'Deploy Prompt Creator Agent to Cloud Run'

on:
  push:
    branches:
      - '"main"'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{secrets.GCP_IDENTITY_PROVIDER}}'
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ secrets.GCP_SEARCHER_CLOUD_RUN_SERVICE }}'
          region: '${{ secrets.GCP_REGION }}'
          secrets: |
                  GOOGLE_GENAI_USE_VERTEXAI=${{ secrets.GOOGLE_GENAI_USE_VERTEXAI }}:latest
                  GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}:latest
                  MAILGUN_SMTP_LOGIN=${{ secrets.MAILGUN_SMTP_LOGIN }}:latest
                  MAILGUN_SMTP_PASSWORD=${{ secrets.MAILGUN_SMTP_PASSWORD }}:latest
                  LOCAL_AGENT_ADDRESS=${{ secrets.LOCAL_AGENT_ADDRESS }}:latest
                  AGENT_MODEL=${{ secrets.AGENT_MODEL }}:latest
                  KANVAS_API_URL=${{ secrets.KANVAS_API_URL }}:latest
                  KANVAS_APP_ID=${{ secrets.KANVAS_APP_ID }}:latest
                  KANVAS_APP_KEY=${{ secrets.KANVAS_APP_KEY }}:latest
                  KANVAS_USER_EMAIL=${{ secrets.KANVAS_USER_EMAIL }}:latest
                  KANVAS_USER_PASSWORD=${{ secrets.KANVAS_USER_PASSWORD }}:latest
                  RECIPIENTS_EMAIL_ADDRESSES=${{ secrets.RECIPIENTS_EMAIL_ADDRESSES }}:latest
          # NOTE: If using a different source folder, update the image name below:
          source: '${{secrets.AGENT_DOCKERFILE_PATH}}'
          flags: ' 
            --allow-unauthenticated 
            --max-instances 2 
            --min-instances 1
            '

      - name: 'Store output url'
        run: |-
          echo ${{ steps.deploy.outputs.url }} > agent_url.txt

      - name: Upload agent URL
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: agent_url.txt
