name: 'Deploy Prompt Creator Agent to Cloud Run'

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{secrets.GCP_IDENTITY_PROVIDER}}'
          service_account: ${{secrets.GCP_SERVICE_ACCOUNT}}

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ secrets.GCP_SEARCHER_CLOUD_RUN_SERVICE }}'
          region: '${{ secrets.GCP_REGION }}'
          secrets: |
            /secrets/.env=${{ secrets.GCP_SEARCHER_ENV_SECRETS_NAME }}:latest
          source: '${{secrets.AGENT_DOCKERFILE_PATH}}'
          flags: ' 
            --allow-unauthenticated 
            --max-instances 2 
            --min-instances 1
            --network=memod-vpc
            --subnet=memod-vpc
            --vpc-egress=private-ranges-only
            '

      - name: 'Echo output url'
        run: |-
          echo ${{ steps.deploy.outputs.url }}

      # - name: Upload agent URL
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: build-artifact
      #     path: agent_url.txt
